/* TripKhata v0.3.0 FINISH BUILD */
(function(){
  const V='0.3.0';
  function payments(t){t.settlements=t.settlements||[];return t.settlements}
  const baseCalc=window.calc;
  window.calc=function(t){
    const b=baseCalc(t);
    payments(t).forEach(p=>{if(p.status==='void')return;b[p.from]=(b[p.from]||0)+Number(p.amount||0);b[p.to]=(b[p.to]||0)-Number(p.amount||0)});
    Object.keys(b).forEach(k=>{if(Math.abs(b[k])<.005)b[k]=0}); return b;
  };
  function active(t){return t.members.filter(m=>!(t.inactiveMembers||[]).includes(m))}
  function smart(t){
    const b=calc(t),d=[],c=[];Object.entries(b).forEach(([m,v])=>{if(v<-.005)d.push({m,v:-v});else if(v>.005)c.push({m,v})});
    d.sort((a,b)=>b.v-a.v);c.sort((a,b)=>b.v-a.v);const out=[];
    while(d.length&&c.length){const x=d[0],y=c[0],a=Math.min(x.v,y.v);out.push({from:x.m,to:y.m,amount:+a.toFixed(2)});x.v-=a;y.v-=a;if(x.v<.005)d.shift();if(y.v<.005)c.shift()}
    return out;
  }
  function showVersion(){
    document.title='TripKhata v'+V;
    const top=document.querySelector('.topbar');
    document.getElementById('tkv300')?.remove();
    const oldBadge=document.getElementById('tkVersionBadge');
    if(oldBadge) oldBadge.textContent='v'+V;
  }
  function memberLedgerData(name){
    const t=getTrip(),b=calc(t),rows=[];let paid=0,share=0,sent=0,recv=0;
    t.expenses.forEach(e=>{const sh=(e.split||[]).includes(name)?Number(e.amount)/(e.split.length||1):0;
      if(e.payer===name){paid+=Number(e.amount);rows.push({date:e.date,text:'Expense paid: '+e.desc,credit:Number(e.amount)})}
      if(sh){share+=sh;rows.push({date:e.date,text:'Own share: '+e.desc,debit:sh})}
    });
    payments(t).filter(p=>p.status!=='void').forEach(p=>{
      if(p.from===name){sent+=Number(p.amount);rows.push({date:p.date,text:'Paid to '+p.to+' • '+p.mode,credit:Number(p.amount)})}
      if(p.to===name){recv+=Number(p.amount);rows.push({date:p.date,text:'Received from '+p.from+' • '+p.mode,debit:Number(p.amount)})}
    });
    rows.sort((a,b)=>new Date(a.date)-new Date(b.date));
    return {t,b,rows,paid,share,sent,recv,balance:b[name]||0};
  }
  window.shareMemberLedgerV301=function(name){
    const d=memberLedgerData(name),t=d.t;
    let x=`👤 *TripKhata — ${name} Ledger*\n🧳 *Trip:* ${t.name}\n\n`;
    x+=`💳 Expenses Paid: ${t.currency}${fmt(d.paid)}\n`;
    x+=`🧾 Own Share: ${t.currency}${fmt(d.share)}\n`;
    x+=`💸 Settlement Paid: ${t.currency}${fmt(d.sent)}\n`;
    x+=`💰 Settlement Received: ${t.currency}${fmt(d.recv)}\n`;
    x+=`📌 Current Balance: ${d.balance>0?'LENA ':d.balance<0?'DENA ':'CLEAR '}${d.balance===0?'✅':t.currency+fmt(Math.abs(d.balance))}\n\n`;
    x+='*STATEMENT*\n';
    if(!d.rows.length)x+='• No entries\n';
    else d.rows.forEach(r=>x+=`• ${r.text} — ${r.credit?'+':''}${r.debit?'-':''}${t.currency}${fmt(r.credit||r.debit)} (${new Date(r.date).toLocaleDateString()})\n`);
    x+=`\n_Generated by TripKhata v0.3.1_`;
    if(navigator.share)navigator.share({title:'TripKhata — '+name+' Ledger',text:x}).catch(()=>{});
    else{navigator.clipboard?.writeText(x);toastMsg('Member ledger copied — WhatsApp te paste karo')}
  };
  window.pdfMemberLedgerV301=function(name){
    const d=memberLedgerData(name),t=d.t,w=window.open('','_blank');
    w.document.write(`<!doctype html><title>${esc(name)} Ledger</title><style>body{font-family:Arial;max-width:800px;margin:30px auto;padding:0 20px;color:#102147}.sum{display:grid;grid-template-columns:1fr 1fr;gap:10px}.box{padding:12px;border:1px solid #e5e7eb;border-radius:10px}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}@media print{button{display:none}}</style><h1>TripKhata</h1><p>${esc(t.name)} — ${esc(name)} Ledger</p><div class="sum"><div class="box">Expenses Paid<br><b>${t.currency}${fmt(d.paid)}</b></div><div class="box">Own Share<br><b>${t.currency}${fmt(d.share)}</b></div><div class="box">Settlement Paid<br><b>${t.currency}${fmt(d.sent)}</b></div><div class="box">Settlement Received<br><b>${t.currency}${fmt(d.recv)}</b></div></div><h2>Current Balance: ${d.balance>0?'To Receive ':d.balance<0?'To Pay ':'Clear '}${d.balance===0?'₹0':t.currency+fmt(Math.abs(d.balance))}</h2><table><tr><th>Date</th><th>Entry</th><th>Credit</th><th>Debit</th></tr>${d.rows.map(r=>`<tr><td>${new Date(r.date).toLocaleDateString()}</td><td>${esc(r.text)}</td><td>${r.credit?t.currency+fmt(r.credit):''}</td><td>${r.debit?t.currency+fmt(r.debit):''}</td></tr>`).join('')}</table><p><button onclick="print()">Print / Save as PDF</button></p>`);
    w.document.close();
  };

  window.openMemberLedger=function(name){
    const t=getTrip();if(!t)return;const b=calc(t),rows=[];let paid=0,share=0,sent=0,recv=0;
    t.expenses.forEach(e=>{const sh=(e.split||[]).includes(name)?Number(e.amount)/(e.split.length||1):0;
      if(e.payer===name){paid+=Number(e.amount);rows.push({date:e.date,text:'Expense paid: '+e.desc,credit:Number(e.amount)})}
      if(sh){share+=sh;rows.push({date:e.date,text:'Own share: '+e.desc,debit:sh})}
    });
    payments(t).filter(p=>p.status!=='void').forEach(p=>{
      if(p.from===name){sent+=Number(p.amount);rows.push({date:p.date,text:'Paid to '+p.to+' • '+p.mode,credit:Number(p.amount)})}
      if(p.to===name){recv+=Number(p.amount);rows.push({date:p.date,text:'Received from '+p.from+' • '+p.mode,debit:Number(p.amount)})}
    });
    rows.sort((a,b)=>new Date(a.date)-new Date(b.date));
    modalRoot.innerHTML=`<div class="overlay" onclick="if(event.target===this)closeModal()"><div class="sheet"><div class="handle"></div>
    <div class="row"><div><div class="sheettitle">${esc(name)} Ledger / Statement</div><div class="muted small">Complete personal trip history</div></div><div class="grow"></div><button class="iconbtn" onclick="closeModal()">✕</button></div>
    <div class="grid2" style="margin-top:12px"><div class="card" style="margin:0"><div class="muted tiny">Paid Expenses</div><b>${t.currency}${fmt(paid)}</b></div><div class="card" style="margin:0"><div class="muted tiny">Own Share</div><b>${t.currency}${fmt(share)}</b></div><div class="card" style="margin:0"><div class="muted tiny">Settlement Paid</div><b>${t.currency}${fmt(sent)}</b></div><div class="card" style="margin:0"><div class="muted tiny">Settlement Received</div><b>${t.currency}${fmt(recv)}</b></div></div>
    <div class="card"><div class="row"><b class="grow">Current Balance</b><b class="${b[name]>=0?'plus':'minus'}">${b[name]>=0?'+':'-'}${t.currency}${fmt(Math.abs(b[name]||0))}</b></div></div>
    <div class="grid2" style="margin-top:10px"><button class="btn primary" onclick='shareMemberLedgerV301(${JSON.stringify(name)})'>💬 WhatsApp / Share</button><button class="btn soft" onclick='pdfMemberLedgerV301(${JSON.stringify(name)})'>📄 PDF / Print</button></div>
    <div class="card"><div class="cardtitle">Statement Entries</div>${rows.length?rows.map(r=>`<div class="member"><div class="grow"><b>${esc(r.text)}</b><div class="muted tiny">${new Date(r.date).toLocaleString()}</div></div>${r.credit?`<b class="plus">+${t.currency}${fmt(r.credit)}</b>`:''}${r.debit?`<b class="minus">-${t.currency}${fmt(r.debit)}</b>`:''}</div>`).join(''):'<div class="muted small" style="padding:14px 0">No entries yet.</div>'}</div></div></div>`;
  };
  function paymentSheet(from='',to='',amount=''){
    const t=getTrip();modalRoot.innerHTML=`<div class="overlay" onclick="if(event.target===this)closeModal()"><div class="sheet"><div class="handle"></div><div class="sheettitle">Record Settlement Payment</div>
    <div class="grid2"><div><div class="label">From</div><select id="sFrom">${t.members.map(m=>`<option ${m===from?'selected':''}>${esc(m)}</option>`).join('')}</select></div><div><div class="label">To</div><select id="sTo">${t.members.map(m=>`<option ${m===to?'selected':''}>${esc(m)}</option>`).join('')}</select></div></div>
    <div class="label">Amount</div><input id="sAmount" type="number" step="0.01" value="${amount||''}">
    <div class="label">Mode</div><select id="sMode"><option>Cash</option><option>GPay / UPI</option><option>PhonePe</option><option>Paytm</option><option>Bank Transfer</option><option>Other</option></select>
    <div class="label">Reference / Note</div><input id="sRef" placeholder="Optional">
    <button class="btn primary block" style="margin-top:14px" onclick="saveSettlementV300()">Mark as Paid</button></div></div>`;
  }
  window.paymentSheetV300=paymentSheet;
  window.saveSettlementV300=function(){
    const t=getTrip(),from=sFrom.value,to=sTo.value,a=Number(sAmount.value);if(from===to)return alert('From te To same member nahi ho sakde.');if(!a)return alert('Valid amount enter karo.');
    payments(t).push({id:id(),from,to,amount:+a.toFixed(2),mode:sMode.value,ref:sRef.value.trim(),date:new Date().toISOString(),status:'paid'});
    activity(`${from} paid ${t.currency}${a} to ${to} via ${sMode.value}`);save();closeModal();renderTrip();toastMsg('Payment recorded');
  };
  window.showSettlementSheet=function(){
    const t=getTrip(),s=smart(t),ps=payments(t).filter(p=>p.status!=='void');
    modalRoot.innerHTML=`<div class="overlay" onclick="if(event.target===this)closeModal()"><div class="sheet"><div class="handle"></div>
    <div class="row"><div><div class="sheettitle">Smart Settle</div><div class="muted small">Pehla ik receiver clear, fer next</div></div><div class="grow"></div><button class="btn soft" onclick="paymentSheetV300()">+ Payment</button></div>
    <div class="card">${s.length?s.map(p=>`<div class="member"><div class="grow"><b>${esc(p.from)} → ${esc(p.to)}</b><div class="muted tiny">Suggested payment</div></div><b>${t.currency}${fmt(p.amount)}</b><button class="btn primary" style="padding:7px 9px;margin-left:7px" onclick='paymentSheetV300(${JSON.stringify(p.from)},${JSON.stringify(p.to)},${p.amount})'>Pay</button></div>`).join(''):'<div class="badge">✓ Trip Fully Settled</div>'}</div>
    <div class="card"><div class="cardtitle">Payments Already Done</div>${ps.length?ps.map(p=>`<div class="member"><div class="grow"><b>${esc(p.from)} → ${esc(p.to)}</b><div class="muted tiny">${esc(p.mode)} • ${new Date(p.date).toLocaleString()}</div></div><b>${t.currency}${fmt(p.amount)}</b></div>`).join(''):'<div class="muted small">No settlement payments yet.</div>'}</div>
    <div class="grid2"><button class="btn primary" onclick="shareReportV300()">WhatsApp / Share</button><button class="btn soft" onclick="pdfReportV300()">PDF / Print</button></div></div></div>`;
  };
  function reportText(){
    const t=getTrip(),b=calc(t),s=smart(t),total=t.expenses.reduce((a,e)=>a+Number(e.amount),0);let x=`🧳 *TripKhata — ${t.name}*\n\n💰 *Total Trip Expense:* ${t.currency}${fmt(total)}\n👥 *Members:* ${t.members.length}\n\n*CURRENT BALANCE*\n`;
    t.members.forEach(m=>{const v=b[m]||0;x+=`• ${m}: ${v>0?'LENA '+t.currency+fmt(v):v<0?'DENA '+t.currency+fmt(-v):'CLEAR ✅'}\n`});
    x+='\n*WHO SHOULD PAY WHOM*\n';if(!s.length)x+='✅ Sabh da hisab clear hai.\n';else{let last='';s.forEach(p=>{if(p.to!==last){last=p.to;x+=`\n➡️ Pehla *${p.to}* nu clear karo:\n`}x+=`   ${p.from} → ${p.to}: *${t.currency}${fmt(p.amount)}*\n`})}
    x+='\n*ALL EXPENSES*\n';t.expenses.forEach(e=>x+=`• ${e.desc}: ${t.currency}${fmt(e.amount)} — paid by ${e.payer} — split ${e.split.length}\n`);
    const ps=payments(t).filter(p=>p.status!=='void');x+='\n*PAYMENTS ALREADY DONE*\n'+(ps.length?ps.map(p=>`• ${p.from} → ${p.to}: ${t.currency}${fmt(p.amount)} via ${p.mode}`).join('\n'):'• None yet');
    return x+`\n\n_Generated by TripKhata v${V}_`;
  }
  window.shareReportV300=function(){const t=getTrip(),text=reportText();if(navigator.share)navigator.share({title:'TripKhata — '+t.name,text}).catch(()=>{});else{navigator.clipboard?.writeText(text);toastMsg('Report copied — WhatsApp te paste karo')}};
  window.pdfReportV300=function(){
    const t=getTrip(),b=calc(t),s=smart(t),total=t.expenses.reduce((a,e)=>a+Number(e.amount),0),w=window.open('','_blank');
    w.document.write(`<!doctype html><title>TripKhata Report</title><style>body{font-family:Arial;max-width:800px;margin:30px auto;padding:0 20px;color:#102147}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:left}.pay{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee}</style><h1>TripKhata</h1><p>${esc(t.name)} • v${V}</p><h2>Total Trip Expense: ${t.currency}${fmt(total)}</h2><h3>Member Balance</h3><table><tr><th>Member</th><th>Status</th><th>Amount</th></tr>${t.members.map(m=>{const v=b[m]||0;return `<tr><td>${esc(m)}</td><td>${v>0?'To Receive':v<0?'To Pay':'Clear'}</td><td>${t.currency}${fmt(Math.abs(v))}</td></tr>`}).join('')}</table><h3>All Expenses</h3>${t.expenses.map(e=>`<div class="pay"><span>${esc(e.desc)} — Paid by ${esc(e.payer)} — Split ${e.split.length}</span><b>${t.currency}${fmt(e.amount)}</b></div>`).join('')}<h3>Who Pays Whom</h3>${s.length?s.map(p=>`<div class="pay"><span>${esc(p.from)} → ${esc(p.to)}</span><b>${t.currency}${fmt(p.amount)}</b></div>`).join(''):'<p>All settled ✅</p>'}<p><button onclick="print()">Print / Save as PDF</button></p>`);w.document.close();
  };
  window.fullTripV300=function(){
    const t=getTrip(),b=calc(t),total=t.expenses.reduce((a,e)=>a+Number(e.amount),0);
    modalRoot.innerHTML=`<div class="overlay" onclick="if(event.target===this)closeModal()"><div class="sheet"><div class="handle"></div><div class="row"><div><div class="sheettitle">${esc(t.name)} — Full Trip Details</div><div class="muted small">Complete expense + settlement statement</div></div><div class="grow"></div><button class="iconbtn" onclick="closeModal()">✕</button></div>
    <div class="card"><div class="muted small">Total Trip Expense</div><div style="font-size:30px;font-weight:950">${t.currency}${fmt(total)}</div></div>
    <div class="card"><div class="cardtitle">All Expenses</div>${t.expenses.length?t.expenses.map(e=>`<div class="member"><div class="grow"><b>${esc(e.desc)}</b><div class="muted tiny">Paid by ${esc(e.payer)} • Split ${e.split.length} • ${new Date(e.date).toLocaleDateString()}</div></div><b>${t.currency}${fmt(e.amount)}</b></div>`).join(''):'<div class="muted small">No expenses.</div>'}</div>
    <div class="card"><div class="cardtitle">Member Statements</div>${t.members.map(m=>`<div class="member"><div class="avatar">${initials(m)}</div><div class="grow"><b>${esc(m)}</b></div><b class="${b[m]>=0?'plus':'minus'}">${b[m]>=0?'+':'-'}${t.currency}${fmt(Math.abs(b[m]||0))}</b><button class="btn soft" style="padding:7px 9px;margin-left:7px" onclick='openMemberLedger(${JSON.stringify(m)})'>Ledger</button></div>`).join('')}</div>
    <div class="grid2"><button class="btn primary" onclick="shareReportV300()">WhatsApp / Share</button><button class="btn soft" onclick="pdfReportV300()">PDF Report</button></div></div></div>`;
  };
  function enhanceTrip(){
    const t=getTrip();if(!t)return;showVersion();
    document.querySelectorAll('#dashBalances .memberpro').forEach(row=>{
      const txt=row.querySelector('.mname')?.textContent||'',name=t.members.find(m=>txt.toLowerCase().includes(m.toLowerCase()));if(!name)return;
      if(!row.querySelector('.tk300-ledger')){const b=document.createElement('button');b.className='btn soft tk300-ledger';b.textContent='Ledger';b.style.cssText='padding:7px 9px;margin-left:6px;font-size:11px';b.onclick=e=>{e.stopPropagation();openMemberLedger(name)};row.insertBefore(b,row.querySelector('.chev'))}
      row.onclick=e=>{if(!e.target.closest('button'))openMemberLedger(name)};
    });
    if(!document.getElementById('tk300full')){const b=document.createElement('button');b.id='tk300full';b.className='btn dark block';b.style.marginTop='12px';b.textContent='📋 Full Trip Details / Statement';b.onclick=fullTripV300;const card=document.getElementById('dashRecent')?.closest('.sectioncard');(card||document.getElementById('dashRecent')?.parentElement)?.after(b)}
  }
  const oldRenderTrip=window.renderTrip;window.renderTrip=function(){oldRenderTrip();setTimeout(enhanceTrip,0)};
  window.renderActivity=function(){activityList.innerHTML=`<div class="row"><div><div class="cardtitle">Trip Reports</div><div class="muted small">Full statement, settlement & sharing</div></div><div class="grow"></div><span class="badge">v${V}</span></div><div class="card"><button class="btn dark block" onclick="fullTripV300()">📋 Full Trip Details / Statement</button><button class="btn primary block" style="margin-top:9px" onclick="showSettlementSheet()">↕ Smart Settle / Who Pays Whom</button><button class="btn soft block" style="margin-top:9px" onclick="shareReportV300()">💬 WhatsApp / Share Report</button><button class="btn soft block" style="margin-top:9px" onclick="pdfReportV300()">📄 PDF / Print Report</button></div>`};
  window.showActivity=function(){renderActivity();showPage('activity')};
  function mention(){
    const input=document.getElementById('quickInput');if(!input||input.dataset.tk300)return;input.dataset.tk300='1';
    input.addEventListener('input',()=>{document.getElementById('tk300sug')?.remove();const v=input.value,at=v.lastIndexOf('@');if(at<0)return;const tail=v.slice(at+1);if(/\s/.test(tail))return;const q=tail.toLowerCase(),t=getTrip(),list=active(t).filter(m=>!q||m.toLowerCase().startsWith(q));if(!list.length)return;const box=document.createElement('div');box.id='tk300sug';box.style.cssText='position:absolute;z-index:99;left:0;right:0;top:100%;background:#fff;border:1px solid #d0d5dd;border-radius:12px;box-shadow:0 10px 25px rgba(0,0,0,.15);overflow:hidden';input.parentElement.style.position='relative';box.innerHTML=list.map(m=>`<button type="button" data-m="${esc(m)}" style="display:block;width:100%;padding:11px;border:0;border-bottom:1px solid #eee;background:#fff;text-align:left;font-weight:800">@${esc(m)}</button>`).join('');input.parentElement.appendChild(box);box.querySelectorAll('button').forEach(b=>b.onclick=()=>{input.value=v.slice(0,at)+'@'+b.dataset.m+' pay ';box.remove();input.focus()})})
  }
  setInterval(()=>{showVersion();mention();enhanceTrip()},900);
  showVersion();
})();
(function(){
  if(document.getElementById('tk301responsive'))return;
  const s=document.createElement('style');s.id='tk301responsive';
  s.textContent=`
    @media(max-width:430px){
      .topbar{gap:8px;padding-left:12px;padding-right:12px}
      .topbar .brand{font-size:20px}
      .topbar .sub{font-size:11px}
      #tkVersionBadge{font-size:9px!important;padding:4px 6px!important}
      .quickpro-head{flex-wrap:wrap}
      .splitmini{margin-left:56px;min-width:120px;flex:1}
      .quickpro-line{grid-template-columns:minmax(0,1fr) auto}
      .quick-add{min-width:70px;padding:0 14px}
      .member-pro,.member{min-width:0}
      .member-pro-name,.member .grow{min-width:0}
      .tk300-ledger,.tk-v027-ledger,.tk-ledger-btn{flex:0 0 auto}
      .grid2>.btn{min-height:44px;white-space:normal}
    }`;
  document.head.appendChild(s);
})();