plugins { id 'com.android.application' }

android {
    namespace 'com.theposterwala.tripkhata'
    compileSdk 35

    defaultConfig {
        applicationId 'com.theposterwala.tripkhata'
        minSdk 24
        targetSdk 35
        versionCode 1010
        versionName '1.0.10-test'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
